### ISSUE TITLE
Select to view Output field data causes script to run again

### ISSUE THREAD

**Issue by dhubbard-ag** [jneale/Xplore#61]
When a script outputs a JSON structure, Xplore presents top level attributes in Name/Type/Value list - allowing items to be selected.

If an item "name" is selected to view the script runs again ("Loading..." shows) 
if the "Show" option is selected it does not (expands the row).

When in a sub item - if "Result" is selected on breadcrumbs - the script runs again ("Loading..." shows) .

Is there an option to stop this re-running and allow initial output to be examined?

If not it would be useful to have a Settings item to control this behaviour.

Thanks - great tool

**Comment by dhubbard-ag** [comment]
Just to add - I have scripts I am using in Xplore which manipulate data and need to example the output from a specific point-in-time run.  A second run can easily end up with different output, making things hard to diagnose.

**Comment by jneale** [comment]
Thanks for the feedback. This is actually by design and is mainly to prevent system overload from recursive/looping structures. Stepping in one at a time is safe, although you are correct that it does re-run the code. Re-engineering this is not off the table, it's just a bit more complex so probably something for the next major release.

In the meantime, a simple trick I use to see the structure of an object is just to return it as indented JSON - `JSON.stringify(my_var, null, 4)`

You can also just put the object into `gs.debug(my_var)` and it will do it for you so long as you have the Fix Logs setting enabled. (This works for info, warn and error, too with Fix Logs enabled, so long as the function call is in the Xplore script and not in something like a script include that Xplore does not have access to).

**Comment by dhubbard-ag** [comment]
Thanks for the response.  

I confess one of my scripts has a lot of structured data, so the `JSON.stringify(my_var, null, 4)` is a good trick to know, but would then require a lot of searching.  

One of the key benefit (to me) of Xplore is this structured navigation - this issue (and linked) are my thoughts on improving a little.  Happy to wait.

**Comment by jneale** [comment]
New object navigation in v5 addresses this! And you can choose how many levels to explore (up to 10).
